title: Frontier Biz
description: A group of Titainfall 2 players with a focus on forming partys to tackle PvE modes such as Insane or Master.
theme: just-the-docs
color_scheme: fbiz
logo: "/assets/img/logo.png"
favicon_ico: "/assets/img/favicon.ico"
url: https://aaroplayzgaming.com/frontier-biz/
permalink: pretty

aux_links:
  Discord: https://discord.gg/xGFkBv9a5X
  Github: https://github.com/aaronplayz-sys/frontier-biz/
aux_links_new_tab: true

heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/aaronplayz-sys/frontier-biz" # the github URL for your repo
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: orange
  new:
    title: New
    color: green
  note:
    title: Note
    color: purp
  warning:
    title: Warning
    color: red

exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - bin/
  - node_modules/
  - vendor/bundle/
  - vendor
  - README.md
  - LICENSE
  - package.json
  - package-lock.json
  - docker-compose.yml
  - .jekyll-cache/
  - _site/

# Jekyll Minifier and Terser Configuration
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-terser
  - jekyll-imagemagick

terser:
  compress:
    drop_console: true
    dead_code: true
    unused: true
    toplevel: true
  mangle: true
  output:
    comments: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Footer configuration
footer_content: "Copyright Â© 2023-2026 Frontier Biz & aaronplayz-sys. All rights reserved."

# Sitemap configuration
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

imagemagick:
  enabled: true # enables responsive images for your site (recommended, see https://github.com/alshedivat/al-folio/issues/537)
  widths:
    - 800
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".gif"
  output_formats:
    webp: "-quality 85"